import { createClient } from 'npm:@supabase/supabase-js@2';
import { corsHeadersFor, handleOptions } from '../_shared/cors.ts';

// Public, unauthenticated lookup by Stripe checkout session id (the booking-success page's
// only signal). site_orders has no public RLS select policy - it holds customer PII (name,
// email, phone) - so this uses the service_role key and returns only display-safe fields,
// never the full row. The session id itself is the capability: unguessable, generated by
// Stripe, and known only to the customer who was redirected here after paying.
Deno.serve(async (req: Request) => {
  const preflight = handleOptions(req);
  if (preflight) return preflight;

  const cors = corsHeadersFor(req);
  const json = (body: unknown, status = 200) =>
    new Response(JSON.stringify(body), { status, headers: { ...cors, 'Content-Type': 'application/json' } });

  if (req.method !== 'POST') {
    return json({ error: 'Method not allowed' }, 405);
  }

  try {
    const { session_id } = await req.json();
    if (!session_id || typeof session_id !== 'string') {
      return json({ error: 'session_id is required' }, 400);
    }

    const supabase = createClient(
      Deno.env.get('SUPABASE_URL')!,
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,
    );

    const { data: order, error } = await supabase
      .from('site_orders')
      .select(
        'status, ticket_code, customer_name, quantity, site_ticket_tiers(name), site_events(title, venue_name, start_date)',
      )
      .eq('stripe_checkout_session_id', session_id)
      .maybeSingle();

    if (error || !order) {
      return json({ status: 'not_found' });
    }

    if (order.status !== 'paid' || !order.ticket_code) {
      return json({ status: order.status });
    }

    const tier = order.site_ticket_tiers as unknown as { name: string } | null;
    const event = order.site_events as unknown as { title: string; venue_name: string; start_date: string } | null;

    return json({
      status: 'paid',
      ticket: {
        ticketCode: order.ticket_code,
        customerName: order.customer_name,
        quantity: order.quantity,
        tierName: tier?.name ?? '',
        eventTitle: event?.title ?? 'Your event',
        venueName: event?.venue_name ?? '',
        startDate: event?.start_date ?? '',
      },
    });
  } catch (error) {
    console.error('site-booking-status error:', error);
    return json({ error: 'Internal server error' }, 500);
  }
});
